"""Freeze the 25-table ERD v10 baseline.

Revision ID: 20260928_01
Revises: None

DDL is deliberately copied here: later model edits must not change this revision.
Existing v9 databases are preserved separately; this revision does not copy data.
"""
from __future__ import annotations

from alembic import op

revision = "20260928_01"
down_revision = None
branch_labels = None
depends_on = None

TABLE_NAMES: tuple[str, ...] = (
    'sessions',
    'sources',
    'segments',
    'assets',
    'jobs',
    'preflights',
    'documents',
    'document_revisions',
    'proposals',
    'validations',
    'issues',
    'layout_checks',
    'approvals',
    'artifacts',
    'exports',
    'layout_previews',
    'idempotency_keys',
    'cleanup_queue',
    'registered_imports',
    'source_versions',
    'extraction_runs',
    'input_revisions',
    'session_source_selections',
    'impact_reviews',
    'confirmations',
)

DDL: tuple[str, ...] = (
    """CREATE TABLE sessions (
	session_id TEXT NOT NULL,
	owner_id TEXT NOT NULL,
	status TEXT NOT NULL,
	input_revision INTEGER NOT NULL,
	brief_json TEXT NOT NULL,
	selected_source_ids TEXT NOT NULL,
	created_at TEXT NOT NULL,
	last_activity_at TEXT NOT NULL,
	expires_at TEXT NOT NULL,
	closed_at TEXT,
	cleanup_status TEXT,
	purged_at TEXT,
	demo INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (session_id),
	CHECK (demo IN (0,1))
)""",
    """CREATE TABLE sources (
	source_id TEXT NOT NULL,
	session_id TEXT,
	source_version INTEGER NOT NULL,
	scope TEXT NOT NULL,
	name TEXT NOT NULL,
	mime_type TEXT NOT NULL,
	size_bytes INTEGER NOT NULL,
	kind TEXT NOT NULL,
	parse_status TEXT NOT NULL,
	text_available INTEGER NOT NULL,
	image_available INTEGER NOT NULL,
	stored_path TEXT NOT NULL,
	content_hash TEXT NOT NULL,
	warnings_json TEXT DEFAULT '[]' NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT,
	deleted_at TEXT,
	origin_group TEXT,
	document_date TEXT,
	document_date_verified INTEGER,
	date_from_filename TEXT,
	extraction_method TEXT,
	use_as_company_evidence INTEGER DEFAULT 1 NOT NULL,
	hash_verified INTEGER,
	hash_note TEXT,
	is_mock INTEGER DEFAULT 0 NOT NULL,
	imported_at TEXT,
	note TEXT,
	origin_kind TEXT DEFAULT 'real' NOT NULL,
	role TEXT DEFAULT 'evidence' NOT NULL,
	current_run_id TEXT,
	PRIMARY KEY (source_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (origin_kind IN ('real','mock','demo')),
	CHECK (role IN ('evidence','instruction')),
	CHECK ((scope = 'session' AND session_id IS NOT NULL) OR (scope = 'registered' AND session_id IS NULL)),
	FOREIGN KEY(current_run_id, source_id, source_version) REFERENCES extraction_runs (run_id, source_id, source_version)
)""",
    """CREATE TABLE segments (
	segment_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	source_version INTEGER NOT NULL,
	session_id TEXT,
	ordinal INTEGER NOT NULL,
	locator_json TEXT NOT NULL,
	text TEXT NOT NULL,
	created_at TEXT NOT NULL,
	chunk_id TEXT,
	evidence_status TEXT,
	document_date TEXT,
	extraction_method TEXT,
	run_id TEXT,
	PRIMARY KEY (segment_id),
	FOREIGN KEY(source_id) REFERENCES sources (source_id),
	FOREIGN KEY(run_id, source_id, source_version) REFERENCES extraction_runs (run_id, source_id, source_version)
)""",
    """CREATE TABLE assets (
	asset_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	source_version INTEGER NOT NULL,
	scope TEXT NOT NULL,
	session_id TEXT,
	origin TEXT NOT NULL,
	mime_type TEXT NOT NULL,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	content_hash TEXT NOT NULL,
	status TEXT NOT NULL,
	stored_path TEXT NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT,
	deleted_at TEXT,
	photo_id TEXT,
	caption_candidate TEXT,
	selected_as_candidate INTEGER,
	approved_for_external_use INTEGER,
	photo_locator_json TEXT,
	run_id TEXT,
	PRIMARY KEY (asset_id),
	FOREIGN KEY(source_id) REFERENCES sources (source_id),
	FOREIGN KEY(run_id, source_id, source_version) REFERENCES extraction_runs (run_id, source_id, source_version)
)""",
    """CREATE TABLE jobs (
	job_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	kind TEXT NOT NULL,
	status TEXT NOT NULL,
	progress_json TEXT NOT NULL,
	result_ref_json TEXT,
	error_json TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	input_revision INTEGER,
	target_key TEXT,
	PRIMARY KEY (job_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE preflights (
	preflight_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	input_revision INTEGER NOT NULL,
	usable_source_ids TEXT NOT NULL,
	facts_json TEXT NOT NULL,
	issues_json TEXT NOT NULL,
	recommendations_json TEXT NOT NULL,
	can_generate INTEGER NOT NULL,
	confirmed_at TEXT,
	created_at TEXT NOT NULL,
	PRIMARY KEY (preflight_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE documents (
	document_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	current_revision INTEGER NOT NULL,
	title TEXT NOT NULL,
	target_pages INTEGER NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE document_revisions (
	document_id TEXT NOT NULL,
	revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	status TEXT NOT NULL,
	content_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	origin TEXT,
	source_ref TEXT,
	session_id TEXT,
	preflight_id TEXT,
	PRIMARY KEY (document_id, revision),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	FOREIGN KEY(preflight_id) REFERENCES preflights (preflight_id),
	UNIQUE (document_id, revision, session_id)
)""",
    """CREATE TABLE proposals (
	proposal_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	base_document_revision INTEGER NOT NULL,
	base_input_revision INTEGER NOT NULL,
	target_block_ids TEXT NOT NULL,
	kind TEXT NOT NULL,
	instruction TEXT NOT NULL,
	changes_json TEXT NOT NULL,
	status TEXT NOT NULL,
	applied_revision INTEGER,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (proposal_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE validations (
	validation_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	status TEXT NOT NULL,
	issue_ids_json TEXT NOT NULL,
	checks_json TEXT NOT NULL,
	fingerprints_json TEXT NOT NULL,
	base_validation_id TEXT,
	agent_called INTEGER DEFAULT 0 NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (validation_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE issues (
	issue_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	identity_key TEXT NOT NULL,
	scope TEXT NOT NULL,
	code TEXT NOT NULL,
	severity TEXT NOT NULL,
	status TEXT NOT NULL,
	message TEXT NOT NULL,
	source_ids_json TEXT NOT NULL,
	fact_ids_json TEXT NOT NULL,
	block_ids_json TEXT NOT NULL,
	origin TEXT NOT NULL,
	anchor_fingerprint TEXT,
	resolution_json TEXT,
	resolution_history_json TEXT DEFAULT '[]' NOT NULL,
	first_validation_id TEXT,
	last_validation_id TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	layout_format TEXT,
	PRIMARY KEY (issue_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	UNIQUE (document_id, identity_key)
)""",
    """CREATE TABLE layout_checks (
	layout_check_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	format TEXT NOT NULL,
	template_version TEXT NOT NULL,
	render_options_hash TEXT NOT NULL,
	asset_manifest_hash TEXT NOT NULL,
	status TEXT NOT NULL,
	actual_pages INTEGER,
	issue_ids_json TEXT DEFAULT '[]' NOT NULL,
	created_at TEXT NOT NULL,
	layout_ok INTEGER,
	publication_policy_ok INTEGER,
	checks_json TEXT,
	findings_json TEXT,
	fail_reasons_json TEXT,
	renderer TEXT,
	artifact_id TEXT,
	preview_basis TEXT,
	preview_ids_json TEXT,
	job_id TEXT,
	publication_checked_at TEXT,
	warnings_json TEXT,
	publication_blocks_json TEXT,
	demo INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (layout_check_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (demo IN (0,1))
)""",
    """CREATE TABLE approvals (
	approval_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	format TEXT NOT NULL,
	validation_id TEXT NOT NULL,
	layout_check_id TEXT NOT NULL,
	template_version TEXT NOT NULL,
	render_options_hash TEXT NOT NULL,
	asset_manifest_hash TEXT NOT NULL,
	approved_at TEXT NOT NULL,
	approved_by TEXT NOT NULL,
	status TEXT NOT NULL,
	invalidated_at TEXT,
	invalidated_reason TEXT,
	created_at TEXT NOT NULL,
	renderer TEXT,
	artifact_id TEXT,
	publication_checked_at TEXT,
	demo INTEGER DEFAULT 0 NOT NULL,
	confirmation_id TEXT,
	PRIMARY KEY (approval_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (demo IN (0,1)),
	FOREIGN KEY(confirmation_id) REFERENCES confirmations (confirmation_id)
)""",
    """CREATE TABLE artifacts (
	artifact_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	format TEXT NOT NULL,
	stored_path TEXT NOT NULL,
	sha256 TEXT NOT NULL,
	size_bytes INTEGER NOT NULL,
	template_version TEXT NOT NULL,
	render_options_hash TEXT NOT NULL,
	asset_manifest_hash TEXT NOT NULL,
	renderer TEXT NOT NULL,
	actual_pages INTEGER,
	layout_check_id TEXT,
	created_at TEXT NOT NULL,
	demo INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (artifact_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (demo IN (0,1))
)""",
    """CREATE TABLE exports (
	export_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	approval_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	format TEXT NOT NULL,
	status TEXT NOT NULL,
	artifact_id TEXT,
	reuse_key TEXT NOT NULL,
	attempt INTEGER DEFAULT 1 NOT NULL,
	job_id TEXT,
	expires_at TEXT NOT NULL,
	error_json TEXT,
	renderer TEXT,
	publication_checked_at TEXT,
	finalized_reason TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	published_at TEXT,
	demo INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (export_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (demo IN (0,1))
)""",
    """CREATE TABLE layout_previews (
	asset_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	layout_check_id TEXT NOT NULL,
	artifact_id TEXT,
	page_no INTEGER NOT NULL,
	stored_path TEXT NOT NULL,
	sha256 TEXT NOT NULL,
	size_bytes INTEGER NOT NULL,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	mime_type TEXT NOT NULL,
	status TEXT DEFAULT 'ready' NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT,
	deleted_at TEXT,
	PRIMARY KEY (asset_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id)
)""",
    """CREATE TABLE idempotency_keys (
	idem_key TEXT NOT NULL,
	owner_id TEXT NOT NULL,
	path TEXT NOT NULL,
	body_hash TEXT NOT NULL,
	status_code INTEGER NOT NULL,
	response_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	session_id TEXT,
	purged_at TEXT,
	PRIMARY KEY (idem_key, owner_id, path)
)""",
    """CREATE TABLE cleanup_queue (
	task_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	kind TEXT NOT NULL,
	target_rel TEXT NOT NULL,
	status TEXT NOT NULL,
	attempt INTEGER DEFAULT 0 NOT NULL,
	next_retry_at TEXT NOT NULL,
	last_error TEXT,
	claimed_by TEXT,
	claimed_at TEXT,
	claim_token TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	done_at TEXT,
	PRIMARY KEY (task_id)
)""",
    """CREATE TABLE registered_imports (
	import_id TEXT NOT NULL,
	bundle_label TEXT NOT NULL,
	with_mock INTEGER NOT NULL,
	dry_run INTEGER NOT NULL,
	summary_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	PRIMARY KEY (import_id)
)""",
    """CREATE TABLE source_versions (
	source_id TEXT NOT NULL,
	version INTEGER NOT NULL,
	session_id TEXT,
	original_name TEXT NOT NULL,
	mime_type TEXT NOT NULL,
	size_bytes INTEGER NOT NULL,
	stored_path TEXT NOT NULL,
	content_hash TEXT NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT,
	purged_at TEXT,
	provenance TEXT NOT NULL,
	PRIMARY KEY (source_id, version),
	FOREIGN KEY(source_id) REFERENCES sources (source_id),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (version >= 1),
	CHECK (size_bytes >= 0)
)""",
    """CREATE TABLE extraction_runs (
	run_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	source_version INTEGER NOT NULL,
	session_id TEXT,
	method TEXT NOT NULL,
	status TEXT NOT NULL,
	warnings_json TEXT DEFAULT '[]' NOT NULL,
	summary_json TEXT DEFAULT '{}' NOT NULL,
	page_count INTEGER,
	created_at TEXT NOT NULL,
	completed_at TEXT,
	purged_at TEXT,
	PRIMARY KEY (run_id),
	FOREIGN KEY(source_id, source_version) REFERENCES source_versions (source_id, version),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	UNIQUE (run_id, source_id, source_version),
	CHECK (page_count IS NULL OR page_count >= 0)
)""",
    """CREATE TABLE input_revisions (
	session_id TEXT NOT NULL,
	revision INTEGER NOT NULL,
	brief_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	provenance TEXT DEFAULT 'request' NOT NULL,
	purged_at TEXT,
	PRIMARY KEY (session_id, revision),
	FOREIGN KEY(session_id) REFERENCES sessions (session_id),
	CHECK (revision >= 1)
)""",
    """CREATE TABLE session_source_selections (
	session_id TEXT NOT NULL,
	input_revision INTEGER NOT NULL,
	source_id TEXT NOT NULL,
	source_version INTEGER NOT NULL,
	run_id TEXT,
	PRIMARY KEY (session_id, input_revision, source_id),
	FOREIGN KEY(session_id, input_revision) REFERENCES input_revisions (session_id, revision),
	FOREIGN KEY(source_id, source_version) REFERENCES source_versions (source_id, version),
	FOREIGN KEY(run_id, source_id, source_version) REFERENCES extraction_runs (run_id, source_id, source_version)
)""",
    """CREATE TABLE impact_reviews (
	review_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	from_input_revision INTEGER NOT NULL,
	to_input_revision INTEGER NOT NULL,
	preflight_id TEXT,
	items_json TEXT DEFAULT '[]' NOT NULL,
	status TEXT NOT NULL,
	created_at TEXT NOT NULL,
	completed_at TEXT,
	purged_at TEXT,
	PRIMARY KEY (review_id),
	FOREIGN KEY(document_id, document_revision, session_id) REFERENCES document_revisions (document_id, revision, session_id),
	FOREIGN KEY(session_id, from_input_revision) REFERENCES input_revisions (session_id, revision),
	FOREIGN KEY(session_id, to_input_revision) REFERENCES input_revisions (session_id, revision),
	FOREIGN KEY(preflight_id) REFERENCES preflights (preflight_id)
)""",
    """CREATE TABLE confirmations (
	confirmation_id TEXT NOT NULL,
	session_id TEXT NOT NULL,
	document_id TEXT NOT NULL,
	document_revision INTEGER NOT NULL,
	input_revision INTEGER NOT NULL,
	kind TEXT NOT NULL,
	confirmed_by TEXT NOT NULL,
	confirmed_at TEXT NOT NULL,
	issue_id TEXT,
	impact_review_id TEXT,
	validation_id TEXT,
	layout_check_id TEXT,
	artifact_id TEXT,
	reasons_json TEXT DEFAULT '[]' NOT NULL,
	status TEXT DEFAULT 'active' NOT NULL,
	invalidated_at TEXT,
	purged_at TEXT,
	PRIMARY KEY (confirmation_id),
	FOREIGN KEY(document_id, document_revision, session_id) REFERENCES document_revisions (document_id, revision, session_id),
	FOREIGN KEY(session_id, input_revision) REFERENCES input_revisions (session_id, revision),
	FOREIGN KEY(issue_id) REFERENCES issues (issue_id),
	FOREIGN KEY(impact_review_id) REFERENCES impact_reviews (review_id),
	FOREIGN KEY(validation_id) REFERENCES validations (validation_id),
	FOREIGN KEY(layout_check_id) REFERENCES layout_checks (layout_check_id),
	FOREIGN KEY(artifact_id) REFERENCES artifacts (artifact_id),
	CHECK (kind IN ('final_consent', 'warning_ack', 'impact_keep')),
	CHECK (status IN ('active', 'invalidated'))
)""",
    """CREATE INDEX ix_sessions_owner ON sessions (owner_id)""",
    """CREATE INDEX ix_sessions_status_expires ON sessions (status, expires_at)""",
    """CREATE INDEX ix_sources_session ON sources (session_id)""",
    """CREATE INDEX ix_segments_source ON segments (source_id, ordinal)""",
    """CREATE INDEX ix_assets_session ON assets (session_id)""",
    """CREATE INDEX ix_jobs_session ON jobs (session_id)""",
    """CREATE INDEX ix_preflights_session ON preflights (session_id, input_revision)""",
    """CREATE INDEX ix_documents_session ON documents (session_id)""",
    """CREATE INDEX ix_proposals_document ON proposals (document_id, status)""",
    """CREATE INDEX ix_validations_document ON validations (document_id, document_revision, input_revision)""",
    """CREATE INDEX ix_issues_document ON issues (document_id, status)""",
    """CREATE INDEX ix_layout_checks_document ON layout_checks (document_id, document_revision, format)""",
    """CREATE INDEX ix_approvals_document ON approvals (document_id, status)""",
    """CREATE INDEX ix_artifacts_session ON artifacts (session_id)""",
    """CREATE INDEX ix_exports_session ON exports (session_id, status)""",
    """CREATE UNIQUE INDEX ux_exports_active ON exports (reuse_key) WHERE status IN ('queued', 'generating', 'ready')""",
    """CREATE INDEX ix_layout_previews_session ON layout_previews (session_id)""",
    """CREATE INDEX ix_idempotency_session ON idempotency_keys (session_id)""",
    """CREATE INDEX ix_cleanup_queue_status ON cleanup_queue (status, next_retry_at)""",
    """CREATE UNIQUE INDEX ux_cleanup_queue_active ON cleanup_queue (session_id, kind, target_rel) WHERE status IN ('pending', 'running')""",
    """CREATE INDEX ix_source_versions_session ON source_versions (session_id)""",
    """CREATE INDEX ix_extraction_runs_session ON extraction_runs (session_id)""",
    """CREATE INDEX ix_extraction_runs_source ON extraction_runs (source_id, source_version, created_at)""",
    """CREATE INDEX ix_session_source_selections_source ON session_source_selections (source_id, source_version)""",
    """CREATE INDEX ix_impact_reviews_document ON impact_reviews (document_id, document_revision)""",
    """CREATE INDEX ix_impact_reviews_session ON impact_reviews (session_id, status)""",
    """CREATE INDEX ix_confirmations_document ON confirmations (document_id, document_revision, input_revision)""",
    """CREATE INDEX ix_confirmations_session ON confirmations (session_id, status)""",
)


def upgrade() -> None:
    bind = op.get_bind()
    version = bind.exec_driver_sql("PRAGMA user_version").scalar_one()
    if version == 10:
        from app.schema_migrations import validate_baseline

        validate_baseline(bind)
        return
    if version != 0:
        raise ValueError(
            f"Cannot apply ERD v10 baseline to schema version {version}. "
            "Preserve the existing database and initialize a separate empty database."
        )
    objects = bind.exec_driver_sql(
        "SELECT name FROM sqlite_master "
        "WHERE name NOT LIKE 'sqlite_%' AND name != 'alembic_version' "
        "AND tbl_name != 'alembic_version'"
    ).all()
    if objects:
        raise ValueError(
            "Baseline creation requires an empty database; existing schema objects were found."
        )
    for statement in DDL:
        bind.exec_driver_sql(statement)
    bind.exec_driver_sql("PRAGMA user_version=10")


def downgrade() -> None:
    bind = op.get_bind()
    # Scan every business table before the first DROP so no partial deletion occurs.
    populated = [
        name for name in TABLE_NAMES
        if bind.exec_driver_sql(f'SELECT 1 FROM "{name}" LIMIT 1').first() is not None
    ]
    if populated:
        raise ValueError(
            "Cannot remove a populated ERD v10 schema. Preserve the database and "
            "restore a verified backup instead of dropping stored data."
        )
    # The migration environment disables SQLite FK enforcement before BEGIN;
    # the baseline contains intentional cyclic references between history tables.
    for name in reversed(TABLE_NAMES):
        bind.exec_driver_sql(f'DROP TABLE "{name}"')
    bind.exec_driver_sql("PRAGMA user_version=0")
